version: "2"

run:
  timeout: 5m
  skip-dirs:
    - cmd

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - revive

issues:
  exclude-rules:
    - path: 'cmd/.*\.go'
      linters:
        - revive
        - staticcheck
    - path: 'cmd/rotatingcircles/templates/templates\.go'
      linters:
        - revive
